[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fundus = "BmyqR28mW6v9fWiyn7VyA5HLYkGnzg6kHMCVqV6v311u"

[programs.devnet]
fundus = "BmyqR28mW6v9fWiyn7VyA5HLYkGnzg6kHMCVqV6v311u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/mnt/c/Users/ComHuT/.config/solana/my-wallet.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
